### ISSUE TITLE
Binderise the Repo

### ISSUE THREAD

**Issue by psychemedia** [fdschmidt/MandelPy#1]
Hi

If you add a `requirements.txt` file containing the single item `matplotlib`, the repo should run on [MyBinder](https://mybinder.org/) [[docs](https://mybinder.readthedocs.io/en/latest/)].

If you also add a *MyBinder* button the`README`, perhaps even linking directly to the demo notebook, folk could then try out the Mandelbrot code directly.

**Comment by fdschmidt** [comment]
Hi,
sorry, totally missed your message! I haven't used Binder before but it looks interesting and I'll see about adding it! Thank you very much for the suggestion!

**Comment by fdschmidt** [comment]
Done! Thanks again for the suggestions, it's really neat!
